### ISSUE TITLE
v1.0.0-rc.1 lässt sich nicht installieren

### ISSUE THREAD

**Issue by razio80** [iobroker-community-adapters/ioBroker.owntracks#33]
Ich möchte CludMQTT testen und wollte dir RC1 installieren mit:
iobroker i https://github.com/iobroker-community-adapters/ioBroker.owntracks/tarball/v1.0.0-rc.1

_Originally posted by @Zefau in https://github.com/iobroker-community-adapters/ioBroker.owntracks/issues/32#issuecomment-586691126_

Leider kommt folgende Fehlermeldung:

internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type number
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at tools.getFile.tmpFile (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:235:40)
    at WriteStream.request.on.pipe.on (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:441:27)
    at WriteStream.emit (events.js:198:13)
    at lazyFs.close (internal/fs/streams.js:207:14)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)

Kann mir jemand helfen?

**Comment by Zefau** [comment]
Welche js.controller version hast du?

**Comment by Zefau** [comment]
Es muss url sein sehe ich gerade
```
iobroker url https://github.com/iobroker-community-adapters/ioBroker.owntracks/tarball/v1.0.0-rc.1
```

**Comment by razio80** [comment]
Sehr gut. Danke! 
Hat funktioniert
