### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by OXERY** [iobroker-community-adapters/ioBroker.owntracks#34]
Hi there,

got a problem with the iOS App. My phone is connected successfully, but the adapter throws following errors:

![image](https://user-images.githubusercontent.com/29032586/78815696-e62ba580-79d0-11ea-8171-f5bf0c01779a.png)

Any ideas on this?

**Comment by FoRealx** [comment]
Hi,

same problem here. I get the error every time I minimize/close the owntracks app.

**Comment by Apollon77** [comment]
Which version do you use?

**Comment by Apollon77** [comment]
Please test 0.6.3 from Github

**Comment by OXERY** [comment]
It is now successfully connected. Will give it a try and get back to you :) thx!

**Comment by FoRealx** [comment]
Used 0.6.2 before.

With 0.6.3 the errors are gone. :)

Thank you!

**Comment by EdgarM73** [comment]
Hi there,

I have still the problem with 0.6.3.

I do use iobroker in a docker container, and the adapter keeps stopping and restarting. I can send tracking information to it.
regards


2020-07-07 00:00:48.154  - [31merror[39m: owntracks.0 (7797) uncaught exception: Cannot read property 'toString' of undefined
2020-07-07 00:00:48.155  - [31merror[39m: owntracks.0 (7797) TypeError: Cannot read property 'toString' of undefined
    at Connection.client.on.packet (/opt/iobroker/node_modules/iobroker.owntracks/main.js:228:46)
    at Connection.emit (events.js:198:13)
    at Connection.emitPacket (/opt/iobroker/node_modules/mqtt-connection/connection.js:10:8)
    at Connection.emit (events.js:198:13)
    at Connection.<anonymous> (/opt/iobroker/node_modules/mqtt-connection/connection.js:53:12)
    at Object.onceWrapper (events.js:286:20)
    at Connection.emit (events.js:198:13)
    at addChunk (/opt/iobroker/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/opt/iobroker/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at Connection.Readable.push (/opt/iobroker/node_modules/readable-stream/lib/_stream_readable.js:245:10)
2020-07-07 00:00:48.156  - [32minfo[39m: owntracks.0 (7797) cleaned everything up...
2020-07-07 00:00:48.159  - [32minfo[39m: owntracks.0 (7797) Client [mqtt_39708b9b.67a1c4] closed
2020-07-07 00:00:48.166  - [32minfo[39m: owntracks.0 (7797) terminating
2020-07-07 00:00:48.167  - [32minfo[39m: owntracks.0 (7797) Terminated (NO_ERROR): Without reason
